name: Build and Test

on:
  push:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    
    - name: build
      run: dotnet build -c Release src/Dahomey.ExpressionEvaluator
    
    - name: test
      run: dotnet test -c Release src/Dahomey.ExpressionEvaluator.Tests
